name: Python CD

on:
  pull_request:
    branches: [ main ]
    types: [closed]

jobs:
  run-tests:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main' && github.event.pull_request.head.ref == 'development'
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
  
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.14.1"
  
      - name: Install dependencies
        run: pip install -r requirements.txt
  
      - name: Run tests
        run: pytest

      - name: Run tests with coverage and html report
        run: pytest --cov=. --cov-report=term --cov-report=xml --html=report.html

      - name: Prepare the webpage
        run: |
          mkdir sites
          mv report.html sites/
          mv coverage.xml sites/
      
      - name: upload the artifacts
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./sites

  deploy:
    needs: run-tests
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main' && github.event.pull_request.head.ref == 'development'
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - name: deploy the artifacts
        uses: actions/deploy-pages@v4
